version: '3.9'
services:

  database:
    image: mysql:8.0
    container_name: radio-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: radio
      MYSQL_DATABASE: radio
      MYSQL_USER: radio
      MYSQL_PASSWORD: radio

  website:
    build:
      context: ../
      dockerfile: setup/Dockerfile
    image: radio-app
    container_name: radio-app
    volumes:
      - ../:/app
    ports:
      - "8080:80"
    depends_on:
      - database
      